### ISSUE TITLE
How to create custom attributes for a custom component that can be assigned from XML in HarmonyOS?

### ISSUE THREAD

**Issue by Sanku-Yogesh** [applibgroup/HarmonyOS-Knowledgebase#11]
### Describe the query
I am implementing a custom component and trying to take input from XML for an attribute. In Android, it looks something like this
```xml
<it.beppi.arcpageindicator.ArcPageIndicator
   android:layout_width="100dp"
   android:layout_height="20dp"
   android:layout_alignParentTop="true"
   android:layout_centerHorizontal="true"
   app:apiViewPager="@id/view_pager"
   app:apiArcOrientation="toDown"
   app:apiAnimationType="cover"
   />
```
How can I do this in HarmonyOS?

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/68543813/how-to-create-custom-attributes-for-a-custom-component-that-can-be-assigned-from

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not Required
Device OS version: Not Required

Regards,
Yogesh.

**Comment by kanaksony** [comment]
Answered and accepted on Stackoverflow.

**Step 1: You need to customize the label app (the name can be customized) in the root layout of the XML file. The format is:** `xmlns:app="http://schemas.huawei.com/res/ohos-auto",and the code is as follows:`

**Step 2: When `ArcPageIndicator` is used in the XML file, define the line custom attribute `apiArcOrientation`. The code is as follows:**

	
	<com.huawei.flowlayout.library.FlowLayout
		......
		app:apiArcOrientation="toDown"
		/>


**Step 3: Obtain the attribute value through AttrSet in the Java code. The code is as follows:**

	public ArcPageIndicator(Context context, AttrSet attrSet) {
		......
		String apiArcOrientation = attrSet.getAttr("apiArcOrientation").get().getStringValue();
	}
