### ISSUE TITLE
How to get the screen width and height of the device in HarmonyOS?

### ISSUE THREAD

**Issue by KomalKalyan** [applibgroup/HarmonyOS-Knowledgebase#12]
### Describe the query
In HarmonyOS, I am trying to create a commonDialog and add a stackLayout of screen size to it. This layout helps me to move a component (for example., an image) to any location on the screen. To do so I need the width and height of the entire screen, how do I get these parameters?

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/68543841/how-to-get-the-screen-width-and-height-of-the-device-in-harmonyos

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not Required
Device OS version: Not Required

Regards,
Komal Kalyan.

**Comment by kanaksony** [comment]
Try these util functions that return Screen width and height. 

	import ohos.agp.utils.Point;
	import ohos.agp.window.service.Display;
	import ohos.agp.window.service.DisplayManager;
	import ohos.app.Context;
	import java.util.Optional;

	public class Utils {

	  private Utils() { }

		public static int getScreenWidth(Context context) {
			DisplayManager displayManager = DisplayManager.getInstance();
			Optional<Display> optDisplay = displayManager.getDefaultDisplay(context);
			Point point = new Point(0, 0);
			if (optDisplay.isPresent()) {
				Display display = optDisplay.get();
				display.getSize(point);
			}
			return (int) point.position[0];
		}

		public static int getScreenHeight(Context context) {
			DisplayManager displayManager = DisplayManager.getInstance();
			Optional<Display> optDisplay = displayManager.getDefaultDisplay(context);
			Point point = new Point(0, 0);
			if (optDisplay.isPresent()) {
				Display display = optDisplay.get();
				display.getSize(point);
			}
			return (int) point.position[1];
		} 
	}
