### ISSUE TITLE
what is the alternative in harmonyos for TypedValue.applyDimension(int unit, float value, android.util.DisplayMetrics metrics)?

### ISSUE THREAD

**Issue by Click2cloud-Eros** [applibgroup/HarmonyOS-Knowledgebase#14]
### Description
I am writing a custom component in HarmonyOS using Java SDK.

I am trying to convert vp to Px.

In Android we can convert dp to px using below code.

```
TypedValue.applyDimension(
                        int unit,
                        float value,
                        android.util.DisplayMetrics metrics)
```
I tried the following code for Harmonyos but not working.

`TypedAttribute.computeTranslateRatio(DeviceCapability devCap)`

### stackoverflow link here:
https://stackoverflow.com/questions/68542357/what-is-the-alternative-in-harmonyos-for-typedvalue-applydimensionint-unit-flo

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1 Beta 4
SDK API version: 5

**Comment by kanaksony** [comment]
Check the API [AttrHelper](https://developer.harmonyos.com/cn/docs/documentation/doc-references/attrhelper-0000001054518726)  for function -
   
`vp2px​(float value, float density)`

or, alternatively you can use -

     public static int dp2px(float dp) {
        return (int) (dp * TypedAttribute.computeTranslateRatio(new DeviceCapability()));
    }
