### ISSUE TITLE
How to automatically slide the pages in page slider HarmonyOS?

### ISSUE THREAD

**Issue by Sanku-Yogesh** [applibgroup/HarmonyOS-Knowledgebase#17]
### Describe the query
I have implemented a custom page slider indicator inspired by [ArcPageIndicator](https://github.com/BeppiMenozzi/ArcPageIndicator/blob/master/sample/src/main/java/it/beppi/arcpageindicator_sample/SampleActivity.java) in HarmonyOS and to test that I wanted to slide the pages using the page slider automatically. How Can I do that in HarmonyOS?

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/68554653/how-to-automatically-slide-the-pages-in-page-slider-harmonyos

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not Required
Device OS version: Not Required

Regards,
Yogesh.

**Comment by kanaksony** [comment]
Replied and accepted on StackOverflow. Hence goo to close!
