### ISSUE TITLE
What is the alternative in HarmonyOS for valueAnimator.removeAllUpdateListeners() in Android OS?

### ISSUE THREAD

**Issue by KomalKalyan** [applibgroup/HarmonyOS-Knowledgebase#18]
### Describe the query
In Android while finishing an animation on valueAnimator, we do the following: 
```java
void end() { 
     // Code for final state of the animation
     valueAnimator.removeAllUpdateListeners(); 
} 
```
What is the alternative for the above code snippet in HarmonyOS? 

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/68540112/what-is-the-alternative-in-harmonyos-for-activity-findviewbyidandroid-r-id-cont

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not Required
Device OS version: Not Required

Regards,
Komal Kalyan.

**Comment by kanaksony** [comment]
Query replied and accepted on StackOverflow.
