### ISSUE TITLE
How to change Element color in HarmonyOS?

### ISSUE THREAD

**Issue by Click2cloud-Eros** [applibgroup/HarmonyOS-Knowledgebase#19]
### Description
I am creating a custom component in HarmonyOS using Java SDK, Where I need to change Element color at runtime.

In Android we have setTint() api to change color of drawable at runtime.

for ex: 
```
drawable.setTint(Color.BLUE); //Require Api level 21
OR
DrawableCompat.setTint(drawable, Color.BLUE);
```

but, In HMOS I saw there is no any api like setTint() or setColor() to change color of Element.

### Stackoverflow link here:
https://stackoverflow.com/questions/68554832/how-to-change-element-color-in-harmonyos

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1 Beta 4
SDK API version: 5

**Comment by kanaksony** [comment]
Please try - 

      public static void setIconColor(Element icon, Color color) {
        int iColor = color.getValue();
        int red   = (iColor & 0xFF0000) / 0xFFFF;
        int green = (iColor & 0xFF00) / 0xFF;
        int blue  = iColor & 0xFF;
        float[] matrix = {
                0, 0, 0, 0, red,
                0, 0, 0, 0, green,
                0, 0, 0, 0, blue,
                0, 0, 0, 1, 0 };
        ColorMatrix colorMatrix = new ColorMatrix();
        colorMatrix.setMatrix(matrix);
        icon.setColorMatrix(colorMatrix);
    }

There are more answers that you can check on stackoverflow.
