### ISSUE TITLE
What is the Alternative for elevation attribute in HarmonyOS?

### ISSUE THREAD

**Issue by Click2cloud-Eros** [applibgroup/HarmonyOS-Knowledgebase#20]
### Description
I am building a HarmonyOS application, Where I need to set elevation on custom component.

In Android we can set elevation on and widget as follow
`android:elevation="8dp"`
but, I saw in HMOS there is no any elevation attribute present for view.

### Stackoverflow link here:
https://stackoverflow.com/questions/68556395/what-is-the-alternative-for-elevation-attribute-in-harmonyos

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1 Beta 4
SDK API version: 5

**Comment by kanaksony** [comment]
This is not yet supported in Java SDK for HarmonyOS but will support these in the near future.
Thanks and stay tuned!

**Comment by GowthamRayar** [comment]
Harmony has **setAltitude** API available from SDK 6, unfortunately which is not released to public yet.
