### ISSUE TITLE
when I use unit(i.e. vp, fp, px) with value in xml file then respective attribute not working ? (HarmonyOS)

### ISSUE THREAD

**Issue by Click2cloud-Eros** [applibgroup/HarmonyOS-Knowledgebase#21]
### Description
I am creating a custom component in HarmonyOS using Java SDK, where I created some attributes for my custom component. Now the problem is "whenever I am trying to set any value in attribute with unit(i.e. vp, fp, px)" then, Respective attribute is not working.

For ex:

```
ohos:iconMargin="8vp"
ohos:text_size="12fp"
ohos:areaMargin="24px"
```
And in my custom component class I get this attribute value like this

```
attr = attrSet.getAttr(areaMargin);
areaMargin = attr.map(Attr::getIntegerValue).orElse(24);
```

### Stackoverflow link here:
https://stackoverflow.com/questions/68558559/when-i-use-uniti-e-vp-fp-px-with-value-in-xml-file-then-respective-attribut

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1 Beta 4
SDK API version: 5

**Comment by kanaksony** [comment]
Replacing `getIntegerValue()` with `getDimensionValue()` should help you.
