### ISSUE TITLE
How to add image to emulator's gallery in HarmonyOS?

### ISSUE THREAD

**Issue by cs1180369** [applibgroup/HarmonyOS-Knowledgebase#23]
### Describe the query
I am testing a HarmonyOS application and want to add an image to the emulator's gallery.

In Android Studio, we can send any file into the android emulator via drag-n-drop action, but drag-n-drop isn't working here.

What is the alternative for this in HarmonyOS?

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/q/68564384/16542616

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not Required
Device OS version: Not Required

Regards,
Jaswanth Ram.

**Comment by kanaksony** [comment]
You can transfer files in HarmonyOS Simulators from your computer via the following command, images will appear in Gallery once pushed -

**Steps**:
1. Make sure the device (Simulator / Phone) is running.
2. Run DevEcoStudio -> Open Terminal.
3. Make sure the Device is connected to DevEcoStudio.
4. Make sure you have HMOS_Home set in environment variables in your computer.
5. Run hdc file send command with arguments. The terminal will show messages with success or failure after execution.

   `hdc file send [LOCAL file path of computer] [REMOTE location in the device]`


**Example**:

![image](https://user-images.githubusercontent.com/6097596/129723895-938f297c-0f43-4918-b9d3-9984b3a7819a.png)

Already answered and accepted on StackOverflow. Hence, closing.
