### ISSUE TITLE
What is the alternative method in Harmony OS for setFirstDayOfWeek() in DatePicker in Android OS? 

### ISSUE THREAD

**Issue by SubhamKarmakar24** [applibgroup/HarmonyOS-Knowledgebase#25]
### Describe the query
I am writing a custom component that allows users to choose a date from the calendar using JAVA SDK. I want to set a day as the first day of the week(e.g. MONDAY), which would then display the calendar with that day as the first day of the week(the first column of Calendar will be that day which was set).

In Android, we have [`setFirstDayOfWeek(int firstDayOfWeek)`](https://developer.android.com/reference/android/widget/DatePicker#setFirstDayOfWeek(int)) method in [DatePicker](https://developer.android.com/reference/android/widget/DatePicker) which does that for us.

What is the alternative for the above in [DatePicker](https://developer.harmonyos.com/en/docs/documentation/doc-references/datepicker-0000001054678716) of Harmony OS?

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/68570836/what-is-the-alternative-method-in-harmony-os-for-setfirstdayofweek-in-datepick

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not required
Device OS version: Not required

Regards,
Subham

**Comment by kanaksony** [comment]
The answer is already replied and accepted on StackOverflow.
