### ISSUE TITLE
How to inflate a layout in HarmonyOS with given context and layout resource id?

### ISSUE THREAD

**Issue by cb3101** [applibgroup/HarmonyOS-Knowledgebase#28]
### Query description
I am working on a HarmonyOS library where I have to inflate a layout with a given layout resource id: int layoutRes and context: Context context.

In android, the same thing is done using

```LayoutInflater.from(context).inflate(layoutRes, this, true);```

What is the alternative for HarmonyOS?
![image](https://user-images.githubusercontent.com/48115293/127617799-f48b3f19-514e-4ed7-bfbd-aa34e1e50835.png)

### Stackoverflow link :
https://stackoverflow.com/questions/68575080/how-to-inflate-a-layout-in-harmonyos-with-given-context-and-layout-resource-id

### Additional information

Developer Platform:  Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not required
Device OS version: Not required

Regards,
Chirag

**Comment by Meknaj** [comment]
LayoutBoost can be used as shown below:
LayoutBoost.inflate(context, layoutRes, this, true);
