### ISSUE TITLE
What is the alternative function in HarmonyOS for onMeasure in Android OS?

### ISSUE THREAD

**Issue by Sanku-Yogesh** [applibgroup/HarmonyOS-Knowledgebase#3]
I am writing a custom component in HarmonyOS using Java SDK.
In order to negotiate the width and height of the custom view in Android, we override [onMeasure()](https://developer.android.com/reference/android/view/View#onMeasure(int,%20int)).
```
@Override
protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {}
```
What is the alternative for the above in HarmonyOS?
Regards,
Yogesh

**Comment by applibengineering** [comment]
Please follow the standard template "API-Functionality Query" in issues in this repository.
