### ISSUE TITLE
What is the alternative method in HarmonyOS for imageview.getImageMatrix( ) in AndroidOS?

### ISSUE THREAD

**Issue by yashwanth-mamilla** [applibgroup/HarmonyOS-Knowledgebase#31]
# Query Description
In Android we will use getImageMatrix( ) method on imageView which returns view's optional matrix. This is applied to the view's drawable when it is drawn. If there is no matrix, this method will return an identity matrix.
In Android

``` 
Matrix matrix = imageView.getImageMatrix( ).
```

What is the alternative for this code snippet in HarmonyOS?

# StackOverFlow Link
 https://stackoverflow.com/questions/68587324/what-is-the-alternative-method-in-harmonyos-for-imageview-getimagematrix-in-a

### Additional information

Developer Platform: [e.g. MAC/Windows]
DevEco Studio version: [e.g. 2.1.0.501]
SDK API version: [e.g. 5]
SDK version: [e.g. 2.1.1.21]
Device: [e.g. Simulator/device]
Device OS version: [go-to about phone and share]

**Comment by kanaksony** [comment]
Already replied and accepted on StackOverFlow!
