### ISSUE TITLE
What is the alternative in harmony OS for Matrix.MTRANS_X or Matrix.MSCALE_X enums in android?

### ISSUE THREAD

**Issue by BharathDakarapu183** [applibgroup/HarmonyOS-Knowledgebase#34]
## Query

In Android for Matrix few enums are predefined such as MSCALE_X, MSCALE_Y, MTRANS_X, MTRANS_Y, MSCEW_X, MSCEW_Y. Do we have any such alternatives in Harmony OS?

## StackOverFlow Link:
**** https://stackoverflow.com/questions/68587598/what-is-the-alternative-in-harmony-os-for-matrix-mtrans-x-or-matrix-mscale-x-enu

### Additional information

Developer Platform: [e.g. MAC/Windows]
DevEco Studio version: [e.g. 2.1.0.501]
SDK API version: [e.g. 5]
SDK version: [e.g. 2.1.1.21]
Device: [e.g. Simulator/device]
Device OS version: [go-to about phone and share]

**Comment by GowthamRayar** [comment]
As Harmony OS rewrites some functionalities/API's in a completely new way from Scratch, you may not have exact API's available in Android. For those functionalities , try extending Harmony API's and write custom behavior of required API.

For your Case extend **ohos.agp.utils.Matrix** API substitute those predefined Enum's.
