### ISSUE TITLE
How to set the Xfermode in Paint object in Harmony OS?

### ISSUE THREAD

**Issue by shreyshrivastava4799** [applibgroup/HarmonyOS-Knowledgebase#35]
### Describe the query
How can we replicate the Android behaviour of this code snippet from [SharpView](https://github.com/zengzhaoxing/SharpView/blob/257cda0e24e43705ec2f48b2cb52f2fd3c447da3/sharpview/src/main/java/com/zhaoxing/view/sharpview/SharpImageView.java#L55) library in Harmony OS?

```
private PorterDuffXfermode mPorterDuffXfermode = new PorterDuffXfermode(PorterDuff.Mode.SRC_IN);

mPaint.setXfermode(mPorterDuffXfermode);
mOutCanvas.drawBitmap(mSoftBitmap.get(), rect, rect, mPaint);
```
### Create the query with harmonyos tag in stackoverflow and share the link here:
**** https://stackoverflow.com/questions/68587830/how-to-set-the-xfermode-in-paint-object-in-harmony-os

### Additional information
Developer Platform: Windows
DevEco Studio version: 2.1.0.501
SDK API version: 5
SDK version: 2.1.1.21
Device: Not required
Device OS version: Not required

**Comment by GowthamRayar** [comment]
**BlendMode** API is the Harmony alternative for **PorterDuffXfermode**.

you can achieve same functionality using,

```java
mPaint.setBlendMode(BlendMode.SRC_IN);
```
