### ISSUE TITLE
What is the HarmonyOS alternative for RecyclerView in android?

### ISSUE THREAD

**Issue by HaritJaiswal** [applibgroup/HarmonyOS-Knowledgebase#37]
### Describe the query
I want to create dynamic lists which can be scrolled on the screen. To do this in Android, we create a custom adapter extending RecyclerView.Adapter<ListItem>, where ListItem is a class containing the content of list items extending RecyclerView.ViewHolder.

How to make such scrollable lists in HarmonyOS?

### Create the query with harmonyos tag in stackoverflow and share the link here:
**** https://stackoverflow.com/questions/68575741/what-is-the-harmonyos-alternative-for-recyclerview-in-android

### Additional information
Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not required
Device OS version: Not required

**Comment by Meknaj** [comment]
You can implement functionality similar to recyclerView using ListContainer and BaseItemprovider
