### ISSUE TITLE
What is the HarmonyOS equivalent of android.graphics.Typeface in Android?

### ISSUE THREAD

**Issue by HaritJaiswal** [applibgroup/HarmonyOS-Knowledgebase#39]
### Describe the query
I am working on a project creating custom fonts using .ttf files. Android uses **Typeface** class to specify the intrinsic style of a font.

What is the HarmonyOS alternative for this?

### Create the query with harmonyos tag in stackoverflow and share the link here:
**** https://stackoverflow.com/questions/68585755/what-is-the-harmonyos-equivalent-of-android-graphics-typeface-in-android

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.501
SDK API version: 5
SDK version: 2.1.1.21
Device: Not required
Device OS version: Not required

**Comment by GowthamRayar** [comment]
**ohos.agp.text.Font** is the HarmonyOS alternative for **Typeface**. Refer following documentation for Usage

https://gitee.com/openharmony-tpc/openharmony_tpc_docs/blob/master/graphics/Typeface.md
