### ISSUE TITLE
What is the alternative function in HarmonyOS for onMeasure in Android OS?

### ISSUE THREAD

**Issue by Sanku-Yogesh** [applibgroup/HarmonyOS-Knowledgebase#4]
### Describe the query
I am writing a custom component in HarmonyOS using Java SDK.
In order to negotiate the width and height of the custom view in Android, we override [onMeasure()](https://developer.android.com/reference/android/view/View#onMeasure(int,%20int)).
```java
@Override
protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {}
```
What is the alternative for the above in HarmonyOS?

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/68524730/what-is-the-alternative-function-in-harmonyos-for-onmeasure-in-android-os

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not Required
Device OS version: Not Required

Regards,
Yogesh.

**Comment by kanaksony** [comment]
Hi @Sanku-Yogesh, 

I have already replied to the above query on Stackoverflow and you have accepted the answer, I would close this issue now.

Thanks,
Kanak
