### ISSUE TITLE
How to set ACCELERATE interpolator for AnimatorValue object in harmonyOS?

### ISSUE THREAD

**Issue by cb3101** [applibgroup/HarmonyOS-Knowledgebase#43]
###  Query description

I am porting one open sources library from Android to HarmonyOS where I have to set ACCELERATE interpolator for AnimatorValue object. The same thing in android using ValueAnimator object is done as below

```
ValueAnimator animator = new ValueAnimator();
animator.setInterpolator(new AccelerateInterpolator());
```

What is the alternative for this in harmonyOS?

### Stackoverflow link:
https://stackoverflow.com/questions/68589185/how-to-set-accelerate-interpolator-for-animatorvalue-object-in-harmonyos

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not required
Device OS version: Not required

Regards,
Chirag

**Comment by GowthamRayar** [comment]
**CurveTypes** are Harmony alternatives for Android **Interpolators**. Example Usage, 

```java
	AnimatorValue animator = new AnimatorValue();
    animator.setCurveType(Animator.CurveType.ACCELERATE);
```

also please refer : https://stackoverflow.com/questions/68589185/how-to-set-accelerate-interpolator-for-animatorvalue-object-in-harmonyos
