### ISSUE TITLE
Alternative for android callback function onSizeChanged()

### ISSUE THREAD

**Issue by yashrajgupta** [applibgroup/HarmonyOS-Knowledgebase#44]
Is there any alternative function for the function onSizeChanged() in android. It Is being used when the dimensions of the layout are changed.

https://stackoverflow.com/questions/68589320/alternative-for-android-callback-function-onsizechanged

### Additional information
Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not Required
Device OS version: Not Required

**Comment by samuel-abhishek** [comment]
According to the team, HarmonyOS does not have alternative function for onSizeChanged() in android by now. Please stay tuned on HarmonyOS official websites.
Answered by Shirley
