### ISSUE TITLE
What is the alternative in harmony OS for imageview.setColorFilter in android?

### ISSUE THREAD

**Issue by anshulgoel72** [applibgroup/HarmonyOS-Knowledgebase#47]
### Describe the query
In android, we can change the color of the drawable by using setColorFilter method. How do we do that in HarmonyOS?

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/68590097/what-is-the-alternative-in-harmony-os-for-imageview-setcolorfilter-in-android

### Additional information

Developer Platform: Windows  
DevEco Studio version: 2.1.0.303  
SDK API version: 5  
SDK version: 2.1.1.21  
Device: Not Required  
Device OS version: Not Required

**Comment by samuel-abhishek** [comment]
setColorFilter(Color) is not directly supported in HMOS. But you may check the below callback in ohos.agp.components.element.Element class,

`public void setColorMatrix​(ColorMatrix matrix)`

which will also change the color of the element(which is equivalent to drawable in android). Please note, here you need to pass the ColorMatrix object as the argument. Please check this [documentation ](https://developer.harmonyos.com/en/docs/documentation/doc-references/element-0000001054358705#ZH-CN_TOPIC_0000001054358705__setColorMatrix-ohos_agp_render_ColorMatrix-)for more info``
