### ISSUE TITLE
How to use Fraction (alternative to Fragment) in Harmony OS?

### ISSUE THREAD

**Issue by shekhar-amit** [applibgroup/HarmonyOS-Knowledgebase#49]
### Describe the query
I want to use fragments in my Harmony OS app, and I saw that [Fraction ](https://developer.harmonyos.com/en/docs/documentation/doc-references/fraction-0000001059908801)is the alternative for it. However, I was unable to find any resource or tutorial as to how to implement it. Can anyone provide an example as to how to use Fraction and FractionAbility to implement Fragments in Harmony OS?

### Create the query with harmonyos tag in stackoverflow and share the link here:
**** https://stackoverflow.com/questions/68590417/how-to-use-fraction-alternative-to-fragment-in-harmony-os

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not required
Device OS version: Not required

**Comment by kanaksony** [comment]
Answered and accepted on StackOverflow.
