### ISSUE TITLE
Is there any alternative for setWindowAnimations(Android) in Harmony OS?[Query]

### ISSUE THREAD

**Issue by alpesh12345** [applibgroup/HarmonyOS-Knowledgebase#51]
### Describe the query
I am developing a Harmony application and I want to animate the Dialog window
this code is from android and this type of animation I want to add
```
Window dialogWindow = dialog.getWindow();
dialogWindow.setWindowAnimations(R.style.CustomDialogAnimation);
```
```
// properties that needs to be attached to Dialog window
duration="75"
fromXScale="0"
fromYScale="0"
toXScale="1"
toYScale="1"
```
I didn't find anything matching documentation like <b>setWindowAnimations</b>.
I tried writing this code but hit a dead end after getting the dialog window. How to add animation properties to this dialog window.
```
CommonDialog commonDialog = new CommonDialog(getContext);
Window dialogWindow = commonDialog.getWindow();
```
Is there any other way to code this?

### Create the query with harmonyos tag in stackoverflow and share the link here:
**** https://stackoverflow.com/questions/68590726/is-there-any-alternative-for-setwindowanimationsandroid-in-harmony-os

### Additional information

Developer Platform: Windows
DevEco Studio version:2.1.0.501
SDK API version: 5
SDK version: 2.1.1.21
Device: Not required
Device OS version: Not required

**Comment by samuel-abhishek** [comment]
According to the team, HarmonyOS does not currently support to add animation properties to dialog window. Please stay tuned on HarmonyOS official websites.
