### ISSUE TITLE
How to transfer the displayed visuals of a component to a temporary canvas in Harmony OS?

### ISSUE THREAD

**Issue by shreyshrivastava4799** [applibgroup/HarmonyOS-Knowledgebase#55]
### Describe the query
In my project, I want to store the currently displayed component in a temporary canvas which I can later reuse. How can I achieve this in Harmony OS?

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/68593223/how-to-transfer-the-display-visuals-of-a-component-to-a-temporary-canvas-in-harm

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not Required
Device OS version: Not Required

**Comment by samuel-abhishek** [comment]
As confirmed by the team, HarmonyOS does not currently support to achieve this. But there are plans to support it in the future. Please stay tuned on HarmonyOS official websites.
Answered By Shirley
