### ISSUE TITLE
What is the alternative function in HarmonyOS for onDraw in Android OS?

### ISSUE THREAD

**Issue by Sanku-Yogesh** [applibgroup/HarmonyOS-Knowledgebase#6]
### Describe the query
I am implementing a custom component in HarmonyOS using Java SDK. In Android to draw a custom view, we override the [onDraw](https://developer.android.com/training/custom-views/custom-drawing#overrideondraw) method from the View class.

In HarmonyOS the Component class doesn’t have the onDraw method. How to resolve it?

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/68542528/what-is-the-alternative-function-in-harmonyos-for-ondraw-in-android-os

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not Required
Device OS version: Not Required

Regards,
Yogesh.

**Comment by applibengineering** [comment]
Query already replied on StackOverflow. So, closing.
