### ISSUE TITLE
Can multiple directional layouts be created?

### ISSUE THREAD

**Issue by rohangupta8756** [applibgroup/HarmonyOS-Knowledgebase#69]
Using DevEco Studio can one directional layout be created in another directional layout ? If Yes how can we do that ?

Stackoverflow link here: https://stackoverflow.com/questions/69084864/can-multiple-directional-layouts-be-created

Developer Platform: [Windows]
DevEco Studio version: [2.1.0.501]
SDK API version: [4]
SDK version: [Java 11]
Device: [Previewer]
Device OS version: [NA]

**Comment by sharathks84** [comment]
Already many members are answered this query. We can close this issue
