### ISSUE TITLE
What is the alternative in HarmonyOS for activity.findViewById(android.R.id.content) in Android OS?

### ISSUE THREAD

**Issue by KomalKalyan** [applibgroup/HarmonyOS-Knowledgebase#7]
### Describe the query
I am writing a helper class to zoom an image in HarmonyOS using Java SDK. To get the current view which is being zoomed in Android we can use `activity.findViewById(android.R.id.content)`.

What is the alternative for the above in HarmonyOS?

### Create the query with harmonyos tag in stackoverflow and share the link here:
https://stackoverflow.com/questions/68540112/what-is-the-alternative-in-harmonyos-for-activity-findviewbyidandroid-r-id-cont

### Additional information

Developer Platform: Windows
DevEco Studio version: 2.1.0.303
SDK API version: 5
SDK version: 2.1.1.21
Device: Not Required
Device OS version: Not Required

Regards,
Komal Kalyan.

**Comment by kanaksony** [comment]
I see a query replied on StackOverflow, so closing it. 

In HarmonyOS we use findComponentById(ResourceTable.Id_xxx) to find any component for the ID passed as param for the api. But in the above case, there is special param i.e. `(android.R.id.content)` which basically passes the root view from the inflated layout. You can directly pass the root id for the same usecase.
