### ISSUE TITLE
Topics in Java that need to revise for better understanding HarmonyOS Trainings

### ISSUE THREAD

**Issue by Muhammed-fazil-k** [applibgroup/HarmonyOS-Knowledgebase#76]
In self-Learning courses, there are Java Courses and Android Courses. If I already know Java, Can i start with the Android Course directly? Which all topics in Java we need to revise for better understanding HarmonyOS Trainings?

**Comment by sharathks84** [comment]
If you are already having basic understanding of OOPS concepts in Java start with Android course.
