### ISSUE TITLE
Download sdk

### ISSUE THREAD

**Issue by Muhammed-fazil-k** [applibgroup/HarmonyOS-Knowledgebase#77]
I can't find the setting option in configure. How to download sdk? After setting up the environment variable how will I know that everything is done?
![Q N  1 (1)](https://user-images.githubusercontent.com/60657039/133448538-fa8bdf06-d3ab-474d-9997-ac15ab3f9b89.jpg)

**Comment by sharathks84** [comment]
First you need to install devEco Studio for Macbook from the link shared.

https://developer.harmonyos.com/en/develop/deveco-studio

Also check this link for installation guide.

https://developer.harmonyos.com/en/docs/documentation/doc-guides/software_install-0000001053582415#section102166218352
