### ISSUE TITLE
While setting up DevEco I am not able to set the HarmonyOS SDK path, What is the issue?

### ISSUE THREAD

**Issue by divya1202** [applibgroup/HarmonyOS-Knowledgebase#78]
1. While setting up DevEco I am not able to set the HarmonyOS SDK path, What is the issue?

![QN  1](https://user-images.githubusercontent.com/90694824/133540636-709c382e-7a4a-4121-ad3c-b96385efe58d.png)
http://https://stackoverflow.com/questions/69201728/while-setting-up-deveco-i-am-not-able-to-set-the-harmonyos-sdk-path-what-is-the

### Additional information

Developer Platform: [e.g. MAC/Windows]
DevEco Studio version: [e.g. 2.1.0.501]
SDK API version: [e.g. 5]
SDK version: [e.g. 2.1.1.21]
Device: [e.g. Simulator/device]
Device OS version: [go-to about phone and share]

**Comment by rohangupta8756** [comment]
@divya1202 
The stackoverflow link isn't working. Do update the same !
And regarding your question - 1. You need to download the Harmony OS SDK, and make sure you fetch it from the right file while setting it up. (Your path is wrong as per my knowledge, Can check with the image attached. )
2. Make sure the SDK and components are in the same folder before using them for set-up.
![image](https://user-images.githubusercontent.com/76242432/133556998-a09c756c-e00d-40b2-a40a-b934e3ea822d.png)
You can get this by File -> Settings -> System Settings -> Harmony OS SDK.

**Comment by sharathks84** [comment]
Hope this issue has been resolved else raise new ticket
