### ISSUE TITLE
Is there a design option for .xml in DevEco Studio?

### ISSUE THREAD

**Issue by devrishikm** [applibgroup/HarmonyOS-Knowledgebase#87]
### Describe the query
In android studio, we get 2 options when we click on a .xml file.
1)Design
2)Test
Do we have similar features in DevEco studio?
I did not find the design option when I click on any .xml file.

### Create the query with harmonyos tag in stackoverflow and share the link here:
**** https://stackoverflow.com/questions/69595005/is-there-a-design-option-for-xml-in-deveco-studio

### Additional information

Developer Platform: Windows
DevEco Studio version:  2.1.0.501
SDK API version: 5
SDK version: 2.1.1.21
Device: Simulator
Device OS version: 2

**Comment by kanaksony** [comment]
Replied on StackOverFlow, so need to close it. @applibengineering please close.
